[[redirects]]
  from = "https://heartbrokendev.com/*"
  to = "https://theheartbrokendev.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.heartbrokendev.com/*"
  to = "https://theheartbrokendev.com/:splat"
  status = 301
  force = true